# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab_files_2025_urbana/urbana.xdc

# XDC: new/bd_wrapper.xdc

# Block Designs: bd/bd/bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd || ORIG_REF_NAME==bd} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_gpio_RGB_0/bd_axi_gpio_RGB_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_RGB_0 || ORIG_REF_NAME==bd_axi_gpio_RGB_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_smc_0/bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_smc_0 || ORIG_REF_NAME==bd_axi_smc_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_timer_0_0/bd_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_timer_0_0 || ORIG_REF_NAME==bd_axi_timer_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_clk_wiz_1_0/bd_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_clk_wiz_1_0 || ORIG_REF_NAME==bd_clk_wiz_1_0} -quiet] -quiet

# IP: bd/bd/ip/bd_mdm_1_0/bd_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mdm_1_0 || ORIG_REF_NAME==bd_mdm_1_0} -quiet] -quiet

# IP: bd/bd/ip/bd_microblaze_0_0/bd_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_microblaze_0_0 || ORIG_REF_NAME==bd_microblaze_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_microblaze_0_axi_intc_0/bd_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_microblaze_0_axi_intc_0 || ORIG_REF_NAME==bd_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/bd/ip/bd_xbar_0/bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_xbar_0 || ORIG_REF_NAME==bd_xbar_0} -quiet] -quiet

# IP: bd/bd/ip/bd_microblaze_0_axi_periph_0/bd_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_microblaze_0_axi_periph_0 || ORIG_REF_NAME==bd_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd/ip/bd_dlmb_bram_if_cntlr_0/bd_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd/ip/bd_dlmb_v10_0/bd_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dlmb_v10_0 || ORIG_REF_NAME==bd_dlmb_v10_0} -quiet] -quiet

# IP: bd/bd/ip/bd_ilmb_bram_if_cntlr_0/bd_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd/ip/bd_ilmb_v10_0/bd_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ilmb_v10_0 || ORIG_REF_NAME==bd_ilmb_v10_0} -quiet] -quiet

# IP: bd/bd/ip/bd_lmb_bram_0/bd_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_lmb_bram_0 || ORIG_REF_NAME==bd_lmb_bram_0} -quiet] -quiet

# IP: bd/bd/ip/bd_microblaze_0_xlconcat_0/bd_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_microblaze_0_xlconcat_0 || ORIG_REF_NAME==bd_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/bd/ip/bd_mig_7series_0_0/bd_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mig_7series_0_0 || ORIG_REF_NAME==bd_mig_7series_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_rst_clk_wiz_1_100M_0/bd_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==bd_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/bd/ip/bd_rst_mig_7series_0_166M_0/bd_rst_mig_7series_0_166M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_rst_mig_7series_0_166M_0 || ORIG_REF_NAME==bd_rst_mig_7series_0_166M_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_timer_1_0/bd_axi_timer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_timer_1_0 || ORIG_REF_NAME==bd_axi_timer_1_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_gpio_0_2/bd_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_0_2 || ORIG_REF_NAME==bd_axi_gpio_0_2} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_gpio_0_3/bd_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_0_3 || ORIG_REF_NAME==bd_axi_gpio_0_3} -quiet] -quiet

# IP: bd/bd/ip/bd_SevenSeg_Urbana_v1_0_0_0/bd_SevenSeg_Urbana_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_SevenSeg_Urbana_v1_0_0_0 || ORIG_REF_NAME==bd_SevenSeg_Urbana_v1_0_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_gpio_0_4/bd_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_0_4 || ORIG_REF_NAME==bd_axi_gpio_0_4} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_gpio_0_5/bd_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_0_5 || ORIG_REF_NAME==bd_axi_gpio_0_5} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_gpio_0_6/bd_axi_gpio_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_0_6 || ORIG_REF_NAME==bd_axi_gpio_0_6} -quiet] -quiet

# IP: bd/bd/ip/bd_clk_wiz_0_0/bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_clk_wiz_0_0 || ORIG_REF_NAME==bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_quad_spi_0_0/bd_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_quad_spi_0_0 || ORIG_REF_NAME==bd_axi_quad_spi_0_0} -quiet] -quiet

# XDC: /home/jashshah/Desktop/Embedded_Lab/Lab_0/jash_project_1/jash_project_1.gen/sources_1/bd/bd/bd_ooc.xdc
